# Generated by Django 4.2.1 on 2023-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('discription', models.TextField()),
                ('tag', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('In QA', 'In QA'), ('Ready', 'Ready'), ('Done', 'Done')], default='New', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
